- name:  install Nginx Web Server
  hosts: frontend
  become: yes
  tasks:
    - name: install Nginx
      ansible.builtin.dnf: 
        name: nginx
        state: present

    - name: Enable & start nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
    
    - name: Remove the default content that web server is serving.
      ansible.builtin.command: rm -rf /usr/share/nginx/html/*

    - name: remove old directory 
      ansible.builtin.file: 
        path: /usr/share/nginx/html
        state: absent

    - name: add directory 
      ansible.builtin.file: 
        path: /usr/share/nginx/html
        state: directory

    - name: unzip 
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copying service
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Restart Nginx Service
      ansible.builtin.service:
        name: nginx
        state: restarted